module.exports = [
  {
    name: 'Arctis 7 2019',
    vendorId: 4152,
    productId: 0x12ad,
    batteryPercentIdx: 2,
    chargingStatusIdx: null,
    micStatusIdx: null,
    writeBytes: [0x06, 0x18],
  },
  {
    name: 'Arctis 7 2017',
    vendorId: 4152,
    productId: 0x1260,
    batteryPercentIdx: 2,
    chargingStatusIdx: null,
    micStatusIdx: null,
    writeBytes: [0x06, 0x18],
  },
  {
    name: 'Arctis Pro',
    vendorId: 4152,
    productId: 0x1252,
    batteryPercentIdx: 2,
    chargingStatusIdx: null,
    micStatusIdx: null,
    writeBytes: [0x06, 0x18],
  },
  {
    name: 'Arctis 1 Wireless',
    vendorId: 4152,
    productId: 0x12b3,
    batteryPercentIdx: 2,
    chargingStatusIdx: null,
    micStatusIdx: null,
    writeBytes: [0x06, 0x18],
  },
  {
    name: 'Arctis 9',
    vendorId: 4152,
    productId: 0x12c2,
    batteryPercentIdx: 3,
    chargingStatusIdx: null,
    micStatusIdx: null,
    writeBytes: [0x06, 0x12],
  },
  {
    name: 'Arctis 7X',
    vendorId: 4152,
    productId: 0x12d7,
    batteryPercentIdx: 3,
    chargingStatusIdx: 4,
    micStatusIdx: 5,
    writeBytes: [0x06, 0x12],
  },
];
