name: Update Homebrew Formula

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Latest Release Info
        id: get_release
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/richrace/arctis-monitor/releases/latest | jq -r .tag_name)
          LATEST_VERSION=${LATEST_TAG#v}
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Compute SHA256 for x86_64
        run: |
          URL_X86="https://github.com/richrace/arctis-monitor/releases/download/${{ env.LATEST_TAG }}/Arctis.Monitor-darwin-x64-${{ env.LATEST_RELEASE }}.zip"
          SHA256_X64=$(curl -L $URL_X86 | sha256sum | awk '{print $1}')
          echo "SHA256_X64=$SHA256_X64" >> $GITHUB_ENV

      - name: Compute SHA256 for arm64
        run: |
          URL_ARM="https://github.com/richrace/arctis-monitor/releases/download/${{ env.LATEST_TAG }}/Arctis.Monitor-darwin-arm64-${{ env.LATEST_RELEASE }}.zip"
          SHA256_ARM=$(curl -L $URL_ARM | sha256sum | awk '{print $1}')
          echo "SHA256_ARM=$SHA256_ARM" >> $GITHUB_ENV

      - name: Update Formula
        run: |
          sed -i "s|url \".*x64.*\"|url \"https://github.com/richrace/arctis-monitor/releases/download/${{ env.LATEST_TAG }}/Arctis.Monitor-darwin-x64-${{ env.LATEST_RELEASE }}.zip\"|" Formula/arctis-monitor.rb
          sed -i "s|sha256 \".*x64.*\"|sha256 \"${{ env.SHA256_X64 }}\"|" Formula/arctis-monitor.rb
          sed -i "s|url \".*arm64.*\"|url \"https://github.com/richrace/arctis-monitor/releases/download/${{ env.LATEST_TAG }}/Arctis.Monitor-darwin-arm64-${{ env.LATEST_RELEASE }}.zip\"|" Formula/arctis-monitor.rb
          sed -i "s|sha256 \".*arm64.*\"|sha256 \"${{ env.SHA256_ARM }}\"|" Formula/arctis-monitor.rb
          sed -i "s|version \".*\"|version \"${{ env.LATEST_RELEASE }}\"|" Formula/arctis-monitor.rb

      - name: Commit & Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Update formula to ${{ env.LATEST_RELEASE }}"
          git push
